"""Second migration

Revision ID: 7efc282c8b43
Revises: a1bd651c6cac
Create Date: 2024-01-29 15:54:49.185263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efc282c8b43'
down_revision: Union[str, None] = 'a1bd651c6cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_resume_vacancy_uc', 'applications', ['resume_id', 'vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_resume_vacancy_uc', 'applications', type_='unique')
    # ### end Alembic commands ###
